# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app
# Copy project metadata and license
COPY pyproject.toml README.md LICENSE MANIFEST.in ./
COPY hatch.toml* ./
# Copy source
COPY src src
# Install mcp-airflow-api
RUN pip install --no-cache-dir .
# Default command for stdio transport
ENTRYPOINT ["mcp-airflow-api"]
