services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: mcp-airflow-api-open-webui
    ports:
      - "${DOCKER_EXTERNAL_PORT_OPENWEBUI}:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  mcp-server:
    image: call518/mcp-server-airflow-api:1.0.0
    container_name: mcp-airflow-api-mcp-server
    ports:
      - "${DOCKER_EXTERNAL_PORT_MCP_SERVER}:8080" ### (WARNING) Must be same with port number of 'FASTMCP_PORT', 'mcp-config.json' and 'mcp-config.json.http'
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - FASTMCP_TYPE=${FASTMCP_TYPE}
      - FASTMCP_HOST=${FASTMCP_HOST}
      - FASTMCP_PORT=${FASTMCP_PORT}
      - AIRFLOW_API_URL=${AIRFLOW_API_URL}
      - AIRFLOW_API_USERNAME=${AIRFLOW_API_USERNAME}
      - AIRFLOW_API_PASSWORD=${AIRFLOW_API_PASSWORD}
      - AIRFLOW_LOG_LEVEL=${AIRFLOW_LOG_LEVEL}
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./.env:/app/.env:ro
    restart: unless-stopped

  mcpo-proxy:
    image: call518/mcpo-proxy-airflow-api:1.0.2
    container_name: mcp-airflow-api-mcpo-proxy
    depends_on:
      - mcp-server
    ports:
      - "${DOCKER_EXTERNAL_PORT_MCPO_PROXY}:8000"
    volumes:
      - ./mcp-config.json.http:/app/config/mcp-config.json
    restart: unless-stopped

volumes:
  open-webui-data:
    name: open-webui-data-mcp-airflow-api
