services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: mcp-airflow-api-open-webui
    ports:
      - "3002:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  # Optional: MCP Proxy Server for tools
  mcpo-proxy:
    image: call518/mcpo-proxy-airflow-api:latest
    container_name: mcp-airflow-api-mcpo-proxy
    ports:
      - "8002:8000"
    volumes:
      - ./mcp-config.json:/app/config/mcp-config.json
      - ./src:/app/src
    restart: always

volumes:
  open-webui-data:
    name: open-webui-data-mcp-airflow-api
