# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Copy necessary files
COPY pyproject.toml README.md ./
COPY src/ ./src/

# Install dependencies and package
RUN pip install --no-cache-dir --upgrade pip hatchling && \
    pip install --no-cache-dir .

# Use non-root user for security
RUN useradd --create-home mcpuser
USER mcpuser

ENTRYPOINT ["mcp-airflow-api"]
